---
kind: pipeline
type: docker
name: publish docker

trigger:
  ref:
    - refs/heads/master
    - refs/tags/*

steps:
  - name: publish
    image: plugins/docker
    settings:
      username: chrispruitt
      password:
        from_secret: docker_password
      repo: chrispruitt/ssm-session
      tags: latest
      squash: true
      auto_tag: true
      cache_from:
        - "chrispruitt/ssm-session:latest"

---
kind: pipeline
type: docker
name: publish docker slim

trigger:
  ref:
    - refs/heads/master
    - refs/tags/*

steps:
  - name: publish
    image: plugins/docker
    settings:
      username: chrispruitt
      password:
        from_secret: docker_password
      repo: chrispruitt/ssm-session
      auto_tag_suffix: slim
      dockerfile: slim.Dockerfile
      squash: true
      auto_tag: true
## TODO add goreleaser pipeline for binary releases
